# Train config preprocess v1.8, split v1.1-s42

run:
  run_name: resnet3d_v1.8_s42

data:
  preprocessed_dir: /mnt/pve/ds_shared/data/preprocess/preprocessed_256x256x32_v1.8
  train_test_split_json: /mnt/pve/work/work-hugo/_splits/full-dataset-v1.1-s42/train_test_split.json

input:
  batch_size: 64

training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 12
  prefetch_factor: 2
  early_stopping_patience: 20
  early_stopping_min_delta: 0.00001

model:
  in_channels: 3

system:
  device: cuda
