# Train config pour preprocess v1.1, split v1.1 — même structure que config.yaml

run:
  run_name: resnet3d_v1.1

data:
  preprocessed_dir: /mnt/pve/ds_shared/data/preprocess/preprocessed_256x256x32_v1.1
  train_test_split_json: /mnt/pve/work/work-hugo/_splits/full-dataset-v1.1/train_test_split.json

input:
  batch_size: 64

training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  num_workers: 12
  prefetch_factor: 2
  early_stopping_patience: null
  early_stopping_min_delta: null

model:
  in_channels: 3

system:
  device: cuda
