# Version identifier
version: "v1.7"

# Optional notes
notes: "MAX | intensity (classique) | intensity_global."

paths:
  dataset_json: "/mnt/pve/ds_shared/dataset_enriched_FINAL.json"
  data_root: "/mnt/pve/ds_shared/data/raw"
  output_dir: "/mnt/pve/ds_shared/data/preprocess"

preprocessing:
  output_format: "nii.gz"

  target_height: 256
  target_width: 256
  target_depth: 32

  patch_extraction:
    mode: "max"

  slice_selection:
    method: "intensity"

  normalization:
    method: "intensity_global"
    data_dir: null
