run:
  run_name: train_vit3d_base_adamw_lr1e4
  runs_root: /home/brunh/scratch_brunh/pfe-ml/_runs
data:
  preprocessed_dir: /home/brunh/scratch_lirmm-ar/PFE_Fiorio/ds_shared/data/hugo_preprocess/preprocessed_256x256x32_v2
  train_test_split_json: /home/brunh/scratch_brunh/pfe-ml/_splits/full-dataset-v1.1/train_test_split.json
  dataset_json: /home/brunh/scratch_lirmm-ar/PFE_Fiorio/ds_shared/ds.json
input:
  batch_size: 8
training:
  epochs: 100
  learning_rate: 0.0001
  optimizer: adamw
  weight_decay: 0.05
  warmup_epochs: 5
  scheduler: cosine
  gradient_clip_val: 1.0
  limit_train_batches: 1.0
  early_stopping:
    enabled: true
    patience: 20
    min_delta: 1.0e-05
model:
  name: vit3d_base
wandb:
  project: resnet3d-binary-classification
  run_name: train_vit3d_base_adamw_lr1e4
  group: train_preprocess_v2
system:
  accelerator: gpu
  devices: 1
  precision: 32-true
