run:
  run_name: train_resnet3d_50
  runs_root: /home/brunh/scratch_brunh/pfe-ml/_runs
data:
  preprocessed_dir: /home/brunh/scratch_lirmm-ar/PFE_Fiorio/ds_shared/data/hugo_preprocess/preprocessed_256x256x32_v3
  train_test_split_json: /home/brunh/scratch_brunh/pfe-ml/_splits/full-dataset-v1.1/train_test_split.json
  dataset_json: /home/brunh/scratch_lirmm-ar/PFE_Fiorio/ds_shared/ds.json
input:
  batch_size: 32
training:
  epochs: 100
  learning_rate: 0.001
  limit_train_batches: 1.0
  early_stopping:
    enabled: true
    patience: 20
    min_delta: 1.0e-05
model:
  name: resnet3d_50
wandb:
  project: resnet3d-binary-classification
  run_name: train_resnet3d_50
  group: train
system:
  accelerator: gpu
  devices: 1
  precision: 32-true
