run:
  run_name: train_convnext3d_large_v2
  runs_root: /mnt/pve/work/work-hugo/_runs
data:
  preprocessed_dir: /mnt/pve/ds_shared/data/preprocess/preprocessed_256x256x32_v2
  train_test_split_json: /mnt/pve/work/work-hugo/_splits/full-dataset-v1.1/train_test_split.json
  dataset_json: /mnt/pve/work/work-hugo/_dataset-json/dataset_final.json
input:
  batch_size: 32
training:
  epochs: 100
  learning_rate: 0.001
  limit_train_batches: 1.0
  early_stopping:
    enabled: true
    patience: 20
    min_delta: 1.0e-05
model:
  name: convnext3d_large
wandb:
  project: gpu-lightning-train
  run_name: train_convnext3d_large
  group: train
system:
  accelerator: gpu
  devices: 1
  precision: 32-true
